[package]
name = "tuff-core"
version = "0.1.0"
edition = "2024"
readme = "README.md"

[dependencies]
libc = "0.2.171"
mach2 = "0.4.2"
raw-cpuid = "11.5.0"
colored = "3.0.0"
hashbrown = "0.16.0"
tabwriter = { version = "1.4.1", features = ["ansi_formatting"] }

paste = { workspace = true }
